name: Build Premium Extension
on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build premium extension
    steps:
    - uses: actions/checkout@v2

    - name: Set environment variables
      id: vars
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "@VERSION@"
        replace: ${{ steps.vars.outputs.branch }}-${{ steps.vars.outputs.sha_short }}
# nothing more