name: Release Premium Extension
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
    secrets:
      DELIVERY_AWS_ACCESS_KEY:
        required: true
      DELIVERY_AWS_SECRET_ACCESS_KEY:
        required: true
      DELIVERY_AWS_S3_BUCKET:
        required: true
      DELIVERY_AWS_REGION:
        required: true
      DELIVERY_WORDPRESS_DEPLOYER_USERNAME:
        required: true
      DELIVERY_WORDPRESS_DEPLOYER_APPLICATION_PASSWORD:
        required: true
      DELIVERY_WORDPRESS_PLUGIN_ENDPOINT:
        required: true
      DELIVERY_WORDPRESS_PRODUCT_ID:
        required: true

jobs:
  variables:
    name: Detect Git and release variables
    uses: dreitier/github-workflows/.github/workflows/variables.yml@main
    with:
      package: ${{ inputs.package }}
      is_official_release: true

  package_and_deploy:
    name: Package and deploy
    runs-on: ubuntu-latest
    needs: variables
    steps:
    - uses: actions/checkout@v2

    - name: Set job variables
      id: zip_variables
      run: |
        echo "zip_file=${ARTIFACT_NAME}.zip"  >> $GITHUB_OUTPUT
      env:
        ARTIFACT_NAME: ${{ needs.variables.outputs.artifact_name }}

    - name: Update version tag
      id: update_version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "@VERSION@"
        include: "**.txt"
        replace: "HELLO WORLD"#${{ needs.variables.outputs.version }}
        regex: false

    - name: "Debug modified files"
      run: |
        echo "Modified files: ${TOTAL}"
        pwd
        ls -al
        cat readme.txt
        touch test.txt
      env:
        TOTAL: ${{ steps.update_version.outputs.modifiedFiles }}

    - name: ZIP workspace
      id: zip
      uses: schakko/action-zip-workspace@main
      with:
        filename: ${{ steps.zip_variables.outputs.zip_file }}
        subdirectory: ${{ needs.variables.outputs.package }}

    - name: Upload release to GitHub
      id: upload
      uses: ncipollo/release-action@v1
      with:
        artifacts:  ${{ steps.zip_variables.outputs.zip_file }}
        allowUpdates: true
        tag: ${{ steps.variables.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to S3
      id: s3_upload
      uses: hkusu/s3-upload-action@v2
      with:
        aws-access-key-id: ${{ secrets.DELIVERY_AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{ secrets.DELIVERY_AWS_SECRET_ACCESS_KEY}}
        aws-bucket: ${{ secrets.DELIVERY_AWS_S3_BUCKET }}
        aws-region: ${{ secrets.DELIVERY_AWS_REGION }}
        file-path: ${{ steps.zip_variables.outputs.zip_file }}
        bucket-root: /
        destination-dir: /${{ needs.variables.outputs.package }}
        output-file-url: 'true'

    - name: Release in WordPress
      id: release
      run: |
        response=$(curl -XPOST --fail -i \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        --user "${{ secrets.DELIVERY_WORDPRESS_DEPLOYER_USERNAME }}:${{ secrets.DELIVERY_WORDPRESS_DEPLOYER_APPLICATION_PASSWORD }}" \
        -d '{
              "artifact_url": "${{ env.ARTIFACT_URL }}",
              "release": { "version": "${{ env.VERSION}}"}
            }' \
          "${{ secrets.DELIVERY_WORDPRESS_PLUGIN_ENDPOINT }}/products/${{ secrets.DELIVERY_WORDPRESS_PRODUCT_ID }}/release")
          
          echo "Response: $response"
      env:
        ARTIFACT_URL: ${{ steps.s3_upload.outputs.file-url }}
        VERSION: ${{ needs.variables.outputs.version }}