name: Detect active Git environment and derive version
on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      is_official_release:
        required: false
        default: false
        type: boolean

    outputs:
      version:
        description: "Version to use, e.g. the official tag or a combination between $branch-$shashort"
        value: ${{ jobs.detect_variables.outputs.version }}

      git_branch:
        description: "Current git branch"
        value: ${{ jobs.detect_variables.outputs.git_branch }}

      git_tag:
        description: "Current git tag"
        value: ${{ jobs.detect_variables.outputs.git_tag }}

      git_sha_short:
        description: "Current git commit hash"
        value: ${{ jobs.detect_variables.outputs.git_sha_short }}

      artifact_name:
        description: "Official artifact name"
        value: ${{ jobs.detect_variables.outputs.artifact_name }}

env:
  # @see https://github.com/actions/runner/issues/1483#issuecomment-1279933184
  IS_OFFICIAL_RELEASE: ${{ inputs.is_official_release == 'true' && 'true' || 'false'  }}

jobs:
  detect_variables:
    runs-on: ubuntu-latest
    name: Detect current variables
    outputs:
      version: ${{ steps.version.outputs.version }}
      git_branch: ${{ steps.git.outputs.branch }}
      git_tag: ${{ steps.git.outputs.tag }}
      git_sha_short: ${{ steps.git.outputs.sha_short }}
      artifact_name: ${{ steps.delivery.outputs.artifact_name }}
      package: ${{ inputs.package }}
        
    steps:
    - uses: actions/checkout@v2

    - name: Set Git variables
      id: git
      run: |
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Set version variable
      id: version
      run: |
        echo "${INPUT_OFFICIAL_RELEASE}"
        echo "${IS_OFFICIAL_RELEASE}"
        if [ "${IS_OFFICIAL_RELEASE}" = "true" ]; then
          echo "version=${TAG}" >> $GITHUB_OUTPUT
        else
          echo "version=${BRANCH}-${SHA_SHORT}" >> $GITHUB_OUTPUT
        fi
      env:
        INPUT_OFFICIAL_RELEASE: ${{ inputs.is_official_release }}
        BRANCH: ${{ steps.git.outputs.branch }}
        TAG: ${{ steps.git.outputs.tag }}
        SHA_SHORT: ${{ steps.git.outputs.sha_short }}
        
    - name: Set delivery variables
      id: delivery
      run: |
        echo "artifact_name=${PACKAGE}-${VERSION}"  >> $GITHUB_OUTPUT
      env:
        PACKAGE: ${{ inputs.package }}
        SUBDIR: ${{ inputs.package }}
        VERSION: ${{ steps.version.outputs.version }}